---
- name: Add fluxcd tap
  become_user: "{{ setup_fluxcd_linuxbrew_user_name }}"
  become: true
  community.general.homebrew_tap:
    name: fluxcd/tap
    state: present

- name: Install flux CLI
  become_user: "{{ setup_fluxcd_linuxbrew_user_name }}"
  become: true
  community.general.homebrew:
    name: fluxcd/tap/flux
    state: present
    update_homebrew: true

- name: Install helm
  become_user: "{{ setup_fluxcd_linuxbrew_user_name }}"
  become: true
  community.general.homebrew:
    name: helm
    state: present
    update_homebrew: true

- name: Install ansible
  become_user: "{{ setup_fluxcd_linuxbrew_user_name }}"
  become: true
  community.general.homebrew:
    name: ansible
    state: present
    update_homebrew: true

- name: "Install linuxbrew"
  ansible.builtin.set_fact:
    run_install_linuxbrew: true
  when: ansible_user_id == "root"
