---
- name: HomeCastle root setup 👑🏗️
  hosts: flimsy-castle-root
  gather_facts: true
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:{{ ansible_env.PATH }}"
  roles:
    - role: mankis_room_create_user
      tags:
        - mankis_room_create_user
        - mankis_room
    - role: mankis_room_setup_zsh
      tags:
        - mankis_room_setup_zsh
        - mankis_room
    - role: mankis_room_setup_oh_my_zsh
      vars:
        mankis_room_setup_oh_my_zsh_copyenv:
          - GITHUB_TOKEN
      tags:
        - mankis_room_setup_oh_my_zsh
        - mankis_room

    - role: setup_install_brew
      tags:
        - setup_install_brew
        - setup
  tasks:
    - name: "Add brew tap"
      become_user: "{{ linuxbrew_user_name }}"
      become: true
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      loop:
        - fluxcd/tap
      tags:
        - setup_install_brew
        - setup

    - name: "Install brew packages"
      become_user: "{{ linuxbrew_user_name }}"
      become: true
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - helm
        - fluxcd/tap/flux
        - ansible
        - gnupg
        - sops
        - age
      tags:
        - setup_install_brew
        - setup
