odroid:
  hosts:
    flimsy-castle-root:
      ansible_host: flimsy-castle
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519_root
    flimsy-castle:
      ansible_host: flimsy-castle
      ansible_user: manki
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    flimsy-castle-group:
      hosts:
        flimsy-castle-root:
        flimsy-castle:
      vars:
        linuxbrew_user_name: "linuxbrew"

        mankis_room_user_name: "manki"
        mankis_room_authorized_key_files:
          - ~/.ssh/id_ed25519.pub

        microk8s_version: "1.32/stable"
        microk8s_primary_user: "manki"

        github_user: "Mankianer"

        flux_gitops:
          repo: "HomeCastles-Crews"
          path: "clusters/flimsy-castle"
          branch: "main"
          private: true
