odroid:
  hosts:
    flimsy-castle-root:
      ansible_host: flimsy-castle
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519_root
      # mankis_room settings
      mankis_room_authorized_key_files:
        - ~/.ssh/id_ed25519.pub
      # microk8s settings
      microk8s_version: "1.32/stable"
      microk8s_primary_user: "manki"
