---
- name: "Run Linuxbrew setup role"
  when: ansible_user_id != "root"
  ansible.builtin.fail:
    msg: "WARNING: Linuxbrew can only be prepared by the root user."

- name: Check brew is installed
  ansible.builtin.command: "brew --version"
  register: brew_version
  changed_when: false
  failed_when: false

- name: "Prepare for linuxbrew installation"
  ansible.builtin.include_tasks:
    file: setup_linuxbrew.yml
  when: brew_version.rc != 0 and ansible_user_id == "root"

- name: "Install linuxbrew"
  ansible.builtin.include_tasks:
    file: install_linuxbrew.yml
  when: brew_version.rc != 0

- name: Check brew is installed
  ansible.builtin.command: "brew --version"
  register: brew_version
  changed_when: false
  when: brew_version.rc != 0
