---
- name: Add fluxcd tap
  become_user: "{{ linuxbrew_user_name }}"
  become: true
  community.general.homebrew_tap:
    name: fluxcd/tap
    state: present

- name: Install flux CLI
  become_user: "{{ linuxbrew_user_name }}"
  become: true
  community.general.homebrew:
    name: fluxcd/tap/flux
    state: present
    update_homebrew: true
