---
- name: Check flux is installed
  ansible.builtin.command: "flux --version"
  register: fluxcd_version
  changed_when: fluxcd_version.rc != 0
  failed_when: false
  notify:
    - Add fluxcd tap
    - Install flux CLI

- name: Show installed flux version
  ansible.builtin.debug:
    msg: "Flux is allready installed with version: {{ fluxcd_version.stdout }}"
  when: fluxcd_version.stdout is defined and fluxcd_version.stdout != ""
