---
- name: Prüfe, ob Flux installiert ist
  ansible.builtin.command: "flux --version"
  register: fluxcd_version
  changed_when: fluxcd_version.rc != 0
  failed_when: false
  notify:
    - Add FluxCD Tap
    - Installiere Flux CLI
    - Check if Flux CLI is installed

- name: Show installed Flux version
  ansible.builtin.debug:
    msg: "Flux is allready installed with version: {{ fluxcd_version.stdout }}"
  when: fluxcd_version.stdout is defined and fluxcd_version.stdout != ""
