---
- name: "Run Linuxbrew setup role"
  when: ansible_user_id != "root"
  ansible.builtin.fail:
    msg: "WARNING: Linuxbrew can only be installed by the root user with this setup."

- name: Check brew is installed
  ansible.builtin.command: "brew --version"
  register: brew_version
  changed_when: brew_version.rc != 0
  failed_when: false
  notify:
    - Install linuxbrew

- name: "Load Linuxbrew role"
  ansible.builtin.import_role:
    name: linuxbrew
  when: run_install_linuxbrew | default(false)

- name: Show installed brew version
  ansible.builtin.debug:
    msg: "Brew is allready installed with version: {{ brew_version.stdout }}"
  when: brew_version.stdout is defined and brew_version.stdout != ""
