---
- name: Ensure brew is installed
  ansible.builtin.include_tasks:
    file: install_flux_cli.yml

- name: Ensure FluxCD is installed
  ansible.builtin.include_tasks:
    file: install_flux_cli.yml

- name: Ensure FluxCD is installed
  ansible.builtin.include_tasks:
    file: install_flux_cli.yml

- name: Ensure helm is installed
  ansible.builtin.include_tasks:
    file: install_helm.yml

- name: Ensure ansible is installed
  ansible.builtin.include_tasks:
    file: install_ansible.yml
