---
- name: Check helm is installed
  ansible.builtin.command: "helm version"
  register: helm_version
  changed_when: false
  failed_when: false

- name: Install helm
  become_user: "{{ linuxbrew_user_name }}"
  become: true
  community.general.homebrew:
    name: helm
    state: present
    update_homebrew: true
  when: helm_version.rc != 0

- name: Check helm is installed
  ansible.builtin.command: "helm version"
  register: helm_version
  changed_when: false
  when: helm_version.rc != 0

- name: Show installed helm version
  ansible.builtin.debug:
    msg: "Helm is already installed with version: {{ helm_version.stdout }}"
  when: helm_version.stdout is defined and helm_version.stdout != ""
