---
- name: Check ansible is installed
  ansible.builtin.command: "ansible --version"
  register: ansible_version_check
  changed_when: false
  failed_when: false

- name: Install ansible
  become_user: "{{ linuxbrew_user_name }}"
  become: true
  community.general.homebrew:
    name: ansible
    state: present
    update_homebrew: true
  when: ansible_version_check.rc != 0

- name: Check ansible is installed
  ansible.builtin.command: "ansible --version"
  register: ansible_version_check
  changed_when: false
  when: ansible_version_check.rc != 0

- name: Show installed ansible version
  ansible.builtin.debug:
    msg: "Ansible is already installed with version: {{ ansible_version_check.stdout }}"
  when: ansible_version_check.stdout is defined and ansible_version_check.stdout != ""
